CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =		Task1-Stack.o

LIBS =

TARGET =	Task1-Stack

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
